### PR TITLE
Bumps version to 0.11.1 and drops the support of Python versions older than 3.7.

### PR DESCRIPTION
**Pull request by cheqianh**
Release workflow failed due to below error. This is because python 3.7 doesn't support this module. So in this PR, we bumps the version to 0.11.1 and drop the support of python versions <3.7.
```
tests/test_benchmark_cli.py:9: in <module>
    from amazon.ionbenchmark.ion_benchmark_cli import TOOL_VERSION
amazon/ionbenchmark/ion_benchmark_cli.py:39: in <module>
    from amazon.ionbenchmark.benchmark_runner import run_benchmark
amazon/ionbenchmark/benchmark_runner.py:13: in <module>
    from amazon.ionbenchmark.sample_dist import SampleDist
amazon/ionbenchmark/sample_dist.py:7: in <module>
    _unit_normal = statistics.NormalDist()
E   AttributeError: module 'statistics' has no attribute 'NormalDist'
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -5,7 +5,7 @@ for Python.
 [![Build Status](https://travis-ci.org/amazon-ion/ion-python.svg?branch=master)](https://travis-ci.org/amazon-ion/ion-python)
 [![Documentation Status](https://readthedocs.org/projects/ion-python/badge/?version=latest)](https://ion-python.readthedocs.io/en/latest/?badge=latest)
 
-This package is designed to work with **Python 3**. It is intended to work with all stable minor versions. Newer language features will be used as deemed valuable. Support may be dropped for versions more than six months past EOL. 
+This package is designed to work with **Python 3.7+**. It is intended to work with all stable minor versions. Newer language features will be used as deemed valuable. Support may be dropped for versions more than six months past EOL.
```
Comment (tgregg) [inline README.md:8]:
```suggestion
This package is designed to work with **Python 3.8+**. Newer language features will be used as deemed valuable. Support may be dropped for versions more than six months past EOL. 
```

File: CHANGES.md [hunk 2]
```diff
@@ -1,3 +1,6 @@
+### 0.11.1 (2023-10-09)
+Drops the support for Python versions older than 3.7.
```
Comment (tgregg) [inline CHANGES.md:2]:
```suggestion
Drops the support for Python versions older than 3.8.
```

Comment (cheqianh) [reply CHANGES.md]: Addressed

File: README.md (hunk 1 above)
Comment (cheqianh) [reply README.md]: addressed

**Review by tgregg — APPROVED** [review]
Squash and merge
